services:
  app:
    image: urlshorten-new:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: h2
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - h2db
  h2db:
    image: oscarfonts/h2
